name: Run Selenium Tests

on: [workflow_dispatch]

jobs:
  run_tests:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: Simeon-Zografov/test-repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome browser
        uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
          version: latest

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: .

      - name: Debugging - Print Chrome Version
        run: google-chrome --version

      - name: Debugging - Print ChromeDriver Version
        run: chromedriver --version

      - name: Run Selenium tests
        run: |
          pytest
        working-directory: .
