name: Run Selenium Tests

on: [workflow_dispatch]

jobs:
  run_tests:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: Simeon-Zografov/test-repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: .

      - name: Run Selenium tests
        continue-on-error: true
        run: |
          pytest
        working-directory: .

      - name: Copy Allure history files
        run: |
          cp -r allure-report/history Reports/history/

      - name: Debug
        run: |
          ls
          cd Reports
          ls
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install allure
          allure --version
          

      - name: Generate Allure report
        run: |
          allure generate Reports --clean

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update Allure report"
          git push origin main