name: Run Selenium Tests and publish report

on:
  workflow_dispatch:
    inputs:
      option:
        description: 'Select test options'
        required: true
        default: 'All'
        type: choice
        options:
          - 'All'
          - 'Accessibility'
          - 'Components'
          - 'Contact list'
          - 'Email reader'
          - 'Landing page'
          - 'Login'
          - 'Social Media Links'
          - 'Visual Tests'
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: Simeon-Zografov/test-repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: .

      - name: Run Selenium tests
        continue-on-error: true
        run: |
          if [[ github.event_name == ''workflow_dispatch'' && github.event.inputs.test_options != 'All' ]]; then
            if [[ github.event.inputs.test_options == ''Accessibility'' ]]; then
              pytest test_Accessibility.py
            fi
            if [[ github.event.inputs.test_options == ''Components'' ]]; then
              pytest test_Components.py
            fi
            if [[ github.event.inputs.test_options == ''Contact list'' ]]; then
              pytest test_ContactList.py
            fi
            if [[ github.event.inputs.test_options == ''Email reader'' ]]; then
              pytest test_EmailReader.py
            fi
            if [[ github.event.inputs.test_options == ''Landing page'' ]]; then
              pytest test_LandingPage.py
            fi
            if [[ github.event.inputs.test_options == ''Login'' ]]; then
              pytest test_Login.py
            fi
            if [[ github.event.inputs.test_options == ''Social Media Links'' ]]; then
              pytest test_SocialMediaLinks.py
            fi
            if [[ github.event.inputs.test_options == ''Visual Tests'' ]]; then
              pytest test_VisualTests.py
            fi
          else
            pytest
          fi
        working-directory: .

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history