name: Run Selenium Tests and publish report

on:
  workflow_dispatch:
    inputs:
      test_options:
        description: 'Select test options'
        required: true
        default: 'All'
        type: string
        options:
          - 'All'
          - 'Accessibility'
          - 'Components'
          - 'Contact list'
          - 'Email reader'
          - 'Landing page'
          - 'Login'
          - 'Social Media Links'
          - 'Visual Tests'
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: Simeon-Zografov/test-repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: .

      - name: Run Selenium tests
        continue-on-error: true
        run: |
          {% if github.event_name == 'workflow_dispatch' %}
            {% set pytest_command = 'pytest' %}
            {% if github.event.inputs.test_options != 'All' %}
              {% for option in github.event.inputs.test_options %}
                {% if option == 'Accessibility' %}
                  {% set pytest_command = pytest_command ~ ' test_Accessibility.py' %}
                {% endif %}
                {% if option == 'Components' %}
                  {% set pytest_command = pytest_command ~ ' test_Components.py' %}
                {% endif %}
                {% if option == 'Contact list' %}
                  {% set pytest_command = pytest_command ~ ' test_ContactList.py' %}
                {% endif %}
                {% if option == 'Email reader' %}
                  {% set pytest_command = pytest_command ~ ' test_EmailReader.py' %}
                {% endif %}
                {% if option == 'Components' %}
                  {% set pytest_command = pytest_command ~ ' test_Components.py' %}
                {% endif %}
                {% if option == 'Landing page' %}
                  {% set pytest_command = pytest_command ~ ' test_LandingPage.py' %}
                {% endif %}
                {% if option == 'Login' %}
                  {% set pytest_command = pytest_command ~ ' test_Login.py' %}
                {% endif %}
                {% if option == 'Social Media Links' %}
                  {% set pytest_command = pytest_command ~ ' test_SocialMediaLinks.py' %}
                {% endif %}
                {% if option == 'Visual Tests' %}
                  {% set pytest_command = pytest_command ~ ' Visual Tests.py' %}
                {% endif %}
              {% endfor %}
            {% endif %}
            {{ pytest_command }}
          {% else %}
            pytest
          {% endif %}
        working-directory: .

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history